import { Link } from 'react-router-dom'
import { useReveal } from '../../hooks/useReveal'

export default function SectorEnterprise() {
  useReveal()
  return (
    <div id="view-svc">
      <section className="svc-hero">
        <div className="wrap">
          <div className="svc-hero-inner">
            <div className="svc-eyebrow reveal">Sector Experience · Large Enterprises</div>
            <h1 className="svc-h1 reveal">Securing the enterprise attack surface at scale.</h1>
            <p className="svc-lede reveal">
              For global enterprises, security is a scale problem. Managing risk across decentralised business units, sprawling legacy infrastructure, and modern cloud environments requires a mature, programmatic approach. We partner with CISOs at tier-one organisations to operationalise governance, secure enterprise AI adoption, and defend massive attack surfaces against advanced adversaries.
            </p>
            <div className="svc-hero-ctas reveal">
              <Link className="btn btn-orange" to="/contact">Book a Briefing <span className="arr">→</span></Link>
              <Link className="btn btn-ghost" to="/sectors">All Sectors <span className="arr">→</span></Link>
            </div>
          </div>
        </div>
      </section>

      <section className="svc-problem section">
        <div className="wrap">
          <div className="svc-problem-grid">
            <div className="svc-problem-left reveal">
              <span className="eyebrow" style={{ color: 'var(--orange)' }}>The Enterprise Challenge</span>
              <h2>Scale amplifies complexity. Complexity breeds vulnerability.</h2>
              <p>Large enterprises do not lack security tools; they lack security cohesion. Decentralised IT procurement leads to shadow IT and shadow AI. Acquisitions introduce inherited technical debt. And the sheer volume of telemetry generated by a global workforce creates alert fatigue that masks real threats. Securing the enterprise requires moving beyond tactical firefighting to strategic maturity management.</p>
            </div>
            <div className="svc-problem-right">
              {[
                { title: 'Shadow AI and Shadow IT', desc: 'Enterprise workforces adopt GenAI and SaaS tools faster than IT can govern them. Without usage assurance frameworks, corporate data flows freely into unmanaged third-party models.' },
                { title: 'The burden of technical debt', desc: 'Legacy systems cannot be secured with modern cloud-native controls. Securing the enterprise requires architectures that protect heritage applications while enabling digital transformation.' },
                { title: 'Regulatory fragmentation', desc: 'Global enterprises must navigate a labyrinth of conflicting regional regulations (GDPR, CCPA, DORA, EU AI Act). A unified compliance framework is essential to avoid audit fatigue.' },
                { title: 'M&A integration risk', desc: 'Enterprises grow through acquisition. Connecting a mature corporate network to an immature, acquired network without rigorous due diligence and isolation introduces systemic risk.' },
              ].map((p, i) => (
                <div className="svc-prob-item reveal" key={i}><h4>{p.title}</h4><p>{p.desc}</p></div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="svc-what section">
        <div className="wrap">
          <div className="section-head reveal" style={{ textAlign: 'left', maxWidth: '640px' }}>
            <span className="eyebrow">Services Most Relevant to This Sector</span>
            <h2>How we secure the enterprise.</h2>
          </div>
          <div className="svc-what-grid">
            {[
              { num: '01', title: 'Enterprise AI Governance', desc: 'We deploy the N3-AIGF framework to discover shadow AI, establish acceptable use policies, and ensure enterprise AI deployments comply with the EU AI Act and ISO 42001.', link: '/what-we-do/ai-governance-security' },
              { num: '02', title: 'Cybersecurity Maturity Management', desc: 'Moving security from subjective opinions to quantified metrics. We assess enterprise security programs against the N3-CMMF to provide board-level visibility into true cyber risk.', link: '/what-we-do/cyber/maturity' },
              { num: '03', title: 'Secure Cloud Architecture', desc: 'Designing zero-trust architectures for complex, multi-cloud environments. We standardise IAM, automate posture management, and secure deployment pipelines.', link: '/what-we-do/platform/cloud-infra' },
              { num: '04', title: 'M&A Cyber Due Diligence', desc: 'Conducting rapid, deep-dive technical due diligence on acquisition targets to quantify cyber risk, estimate remediation costs, and design safe integration strategies.', link: '/what-we-do/cyber/ma' },
              { num: '05', title: 'Penetration Testing & Validation', desc: 'Continuous testing of the external attack surface, internal networks, and critical applications to validate the effectiveness of the enterprise security architecture.', link: '/what-we-do/platform/security-testing' },
              { num: '06', title: 'Fractional CISO & Leadership', desc: 'Providing executive-level security leadership to guide the enterprise through major transformation programmes, regulatory audits, or post-breach recovery.', link: '/what-we-do/cyber/fractional-ciso' },
            ].map((s, i) => (
              <Link className="svc-what-card reveal" to={s.link} key={i} style={{ textDecoration: 'none', cursor: 'pointer' }}>
                <div className="svc-what-num">{s.num}</div>
                <h3 className="svc-what-title">{s.title}</h3>
                <p className="svc-what-desc">{s.desc}</p>
                <span className="arr-link" style={{ marginTop: '12px', display: 'block' }}>Learn more →</span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="svc-standards section">
        <div className="wrap">
          <div className="section-head reveal" style={{ maxWidth: '600px', textAlign: 'left' }}>
            <span className="eyebrow">Frameworks &amp; Standards</span>
            <h2>Enterprise frameworks we work to.</h2>
          </div>
          <div className="standards-grid">
            {['ISO/IEC 27001:2022', 'NIST Cybersecurity Framework (CSF 2.0)', 'CIS Critical Security Controls', 'SOC 2 Type II', 'NIST AI RMF', 'EU AI Act', 'GDPR / CCPA'].map(s => (
              <span className="standard-badge reveal" key={s}>{s}</span>
            ))}
          </div>
        </div>
      </section>

      <section className="svc-related section">
        <div className="wrap">
          <div className="section-head reveal" style={{ maxWidth: '600px', textAlign: 'left' }}>
            <span className="eyebrow">Related Sectors</span>
            <h2>Adjacent to Large Enterprises</h2>
          </div>
          <div className="related-grid">
            <Link className="related-card reveal" to="/sectors/financial-services"><h4>Financial Services</h4><p>Global banks and insurers with similar scale and heightened regulatory complexity.</p><span className="arr-link">Learn more →</span></Link>
            <Link className="related-card reveal" to="/sectors/private-equity"><h4>Private Equity &amp; Investment</h4><p>The acquirers that drive M&A integration and divestiture within the enterprise.</p><span className="arr-link">Learn more →</span></Link>
            <Link className="related-card reveal" to="/sectors/software-saas"><h4>Software &amp; SaaS</h4><p>The vendors supplying the enterprise supply chain who must prove their trust.</p><span className="arr-link">Learn more →</span></Link>
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 0 }}>
        <div className="wrap">
          <div className="cta-band reveal">
            <h2>Enterprise security requires strategic architecture, not just more tools.</h2>
            <p>Speak with practitioners who have managed cyber risk and AI governance for global, multi-national organisations.</p>
            <div className="cta-btns">
              <Link className="btn btn-orange" to="/contact">Book a Briefing <span className="arr">→</span></Link>
              <Link className="btn btn-ghost" to="/sectors">All Sectors</Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
